* README
  :PROPERTIES:
  :CUSTOM_ID: readme
  :END:

This fork of TwoPhaseFlow incorporates some improvements over the original formulation for OpenFOAM v2206:

- Directly specify the pseudo-diffusion coefficient using "diff" in the hardtWondraCoeffs dictionary.
- gradAlpha surface tension model will now use the smoothed gradient of alpha to suppress spurious currents.

The original README is shown below.

* twophaseflow
  :PROPERTIES:
  :CUSTOM_ID: twophaseflow
  :END:

the TwoPhaseFlow Library adds new surface tension and phase change
models to OpenFOAM and provides benchmark cases for verification

** Documentation
   :PROPERTIES:
   :CUSTOM_ID: documentation
   :END:

The available models and solvers are documentated in:

https://arxiv.org/abs/2103.00870

** Getting Started
   :PROPERTIES:
   :CUSTOM_ID: getting-started
   :END:

*** Prerequisites
    :PROPERTIES:
    :CUSTOM_ID: prerequisites
    :END:

Requires OpenFOAM v1812:

#+BEGIN_EXAMPLE
  https://www.openfoam.com/download/release-history.php
#+END_EXAMPLE

The branch of2106 works with of2106

*** Installing
    :PROPERTIES:
    :CUSTOM_ID: installing
    :END:

#+BEGIN_SRC sh
      git clone https://github.com/DLR-RY/TwoPhaseFlow
      cd TwoPhaseFlow
      ./Allwmake
      ./get-gmsh.sh # will install gmsh version 306 as gmshv306
      # for AMR
      git submodule update --init --recursive
      cd modules/multiDimAMR/
      ./Allwmake
#+END_SRC

*** running testsuite
    :PROPERTIES:
    :CUSTOM_ID: running-testsuite
    :END:

make sure that the desired openfoam installation is sourced e.g. v1812
and that python is installed with a version >= 3.6 (miniconda is a great
option, but anaconda works as well)

#+BEGIN_SRC sh
      python -m venv env # creats virtual python enviroments (optional step)
      pip install oftest

      py.test # runs the tests
      py.test --writeNSteps=1 run/ # test all testcases in run
#+END_SRC

** Authors
   :PROPERTIES:
   :CUSTOM_ID: authors
   :END:

- *Henning Scheufler*

*** adaptive mesh refinement with multiple regions
    :PROPERTIES:
    :CUSTOM_ID: adaptive-mesh-refinement-with-multiple-regions
    :END:

AMR with multiple regions does not work in version of1812 but it is
fixed in newer versions.

To fix this apply the patch (assumes openfoam is already source):

#+BEGIN_SRC sh
      cp  patches/multiRegionAMR.patch $WM_PROJECT_DIR
      cp  patches/tableBase.patch $WM_PROJECT_DIR
      cp  patches/surfaceFieldValue.patch $WM_PROJECT_DIR
      cd $WM_PROJECT_DIR
      git apply multiRegionAMR.patch
      git apply tableBase.patch
      git apply surfaceFieldValue.patch
#+END_SRC

details see:

https://develop.openfoam.com/Development/openfoam/-/issues/1676

https://develop.openfoam.com/Development/openfoam/-/issues/1753 ##
License

This project is licensed under the GPL v3 License - see the
[[file:LICENSE.md]] file for details

** running Benchmarks
   :PROPERTIES:
   :CUSTOM_ID: running-benchmarks
   :END:

#+BEGIN_SRC sh
      ./get-gmsh.sh # install gmsh
      pip install casefoam
#+END_SRC

The run/benchmark cases are run with

#+BEGIN_SRC sh
      cd run/benchmark/phaseChange/suckingInterface/
      python genCases.py # generates the study based and template case (here StefanProblem)
      ./Allrun # runs all the created testcases
      python getResults.py # to see results
#+END_SRC

Alternatively, the runAll.sh can be executed in the folder.

Note:

that some cases use the slurm queuing system and call
=sbatch Allrun_Slurm= in the Allrun script, so you might need to modify
it in the template case
